version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Ini akan menghubungkan direktori proyek ke dalam container
    environment:
      - ENV=development  # Anda bisa menambahkan variabel lingkungan lain jika diperlukan

